### ISSUE TITLE
V2Ray搭建详细图文教程

### ISSUE THREAD

**Issue by oldfatdog** [oldfatdog/blog#2]
搭建 V2Ray 看这篇文章就够了！这是完完全全为小白准备的 V2Ray 搭建教程，详细的图文教程确保你可以百分百成功搭建 V2Ray 使用。

## 前言

此 V2Ray 教程完完全全是为小白准备的，从购买 VPS 到使用 SSH 登录并使用 V2Ray 一键安装脚本配置 V2Ray，详细的图文教程确保你可以百分百成功搭建 V2Ray 使用，哪怕你只是一个小白。
由于 V2Ray 的配置对于小白来说是非常不友好的，所以此 V2Ray 教程的 V2Ray 服务器端配置将会使用我本人撰写的 [V2Ray 一键安装脚本](https://github.com/233boy/v2ray/wiki/V2Ray一键安装脚本)，这是一个对小白友好的 V2Ray 一键脚本，简化 V2Ray 安装和部署，并且自动开启 BBR 优化，当然你也可以手动打开 BBR 来优化 V2Ray，也可以选择使用锐速来 优化 V2Ray。

## V2Ray 简介

官网：[https://www.v2ray.com](https://www.v2ray.com/)

[V2Ray(Project V)](https://www.v2ray.com/) 相对于 Shadowsocks，V2Ray 更像全能选手，拥有更多可选择的协议 / 传输载体 (Socks、HTTP、TLS、TCP、mKCP、WebSocket )，还有强大的路由功能，不仅仅于此，它亦包含 Shadowsocks 组件，你只需要安装 V2Ray，你就可以使用所有的 V2Ray 相关的特性包括使用 Shadowsocks，由于 V2Ray 是使用 GO 语言所撰写的，天生的平台部署优势，下载即可使用，当然啦，由于 V2Ray 的配置相对来说是很繁琐的，毫无夸张的说，但是有了本人所写的 [V2Ray 一键安装脚本](https://github.com/233boy/v2ray/wiki/V2Ray一键安装脚本) 加持下，使用 V2Ray 便会显得轻松多了。

## 备注

总结一下此文章的大致流程，此 V2Ray 教程可百分百帮助你搭建 V2Ray 使用。哪怕你只是一个小白。

-   购买一个 VPS
    想要搭建 V2Ray，就必须要拥有一台 VPS。

-   获取 VPS 信息
    我们必须要知道 VPS IP 地址，root 用户密码，SSH 端口

-   安装 Xshell
    Xshell 是一个 SSH 客户端，要登录 VPS，当然需要 SSH 客户端

-   登录 VPS
    使用 Xshell 配置 VPS SSH 信息，然后登录

-   安装 V2Ray
    安装过程你可以随意选择你喜欢的传输协议或者配置 Shadowsocks

-   V2Ray 安装完成
    此时你可以使用客户端配置 V2Ray 使用了

-   V2Ray 高级玩法
    配置 WebSocket + TLS ， HTTP/2 ， mKCP 等

    

## 购买一个VPS

想要搭建 V2Ray， 拥有一个 VPS 是必需的。
我们推荐使用：[搬瓦工（Bandwagon Host）](https://on.affpass.com/go/bwg) VPS 来搭建 V2Ray，搬瓦工是一个对中国用户极度友好的 VPS 商家，有香港，CN2 GIA 等线路，支持支付宝付款，当然也是支持退款的！

>   备注：按住 Ctrl + 单击， 即可在新窗口打开链接

推荐购买的搬瓦工套餐如下

| 线路    | CPU   | 内存     | 硬盘    | 带宽      | 流量         | 价格              | 链接                                     |
| ------- | ----- | -------- | ------- | --------- | ------------ | ----------------- | ---------------------------------------- |
| 香港    | 2 核  | 2048 MB  | 40 GB   | 1 G       | 500GB / 月   | **$89.99 / 月**   | [购买](https://on.affpass.com/go/bwg/95) |
| 香港    | 4 核  | 4096 MB  | 80 GB   | 1 G       | 1000GB / 月  | $155.99 / 月      | [购买](https://on.affpass.com/go/bwg/96) |
| 香港    | 6 核  | 8192 MB  | 160 GB  | 1 G       | 2000GB / 月  | $299.99 / 月      | [购买](https://on.affpass.com/go/bwg/97) |
| 香港    | 8 核  | 16384 MB | 320 GB  | 1 G       | 4000GB / 月  | $589.99 / 月      | [购买](https://on.affpass.com/go/bwg/98) |
| -       | -     | -        | -       | -         | -            | -                 | -                                        |
| CN2 GIA | 2 核  | 1 GB     | 20 GB   | **2.5 G** | 1000GB / 月  | **$65.99 / 半年** | [购买](https://on.affpass.com/go/bwg/87) |
| CN2 GIA | 3 核  | 2 GB     | 40 GB   | **2.5 G** | 2000GB / 月  | $69.99 / 季       | [购买](https://on.affpass.com/go/bwg/88) |
| CN2 GIA | 4 核  | 4 GB     | 80 GB   | **2.5 G** | 3000GB / 月  | $49.99 / 月       | [购买](https://on.affpass.com/go/bwg/89) |
| CN2 GIA | 6 核  | 8 GB     | 160 GB  | **5 G**   | 5000GB / 月  | $75.99 / 月       | [购买](https://on.affpass.com/go/bwg/90) |
| CN2 GIA | 8 核  | 16 GB    | 320 GB  | **5 G**   | 8000GB / 月  | $139.99 / 月      | [购买](https://on.affpass.com/go/bwg/91) |
| CN2 GIA | 10 核 | 32 GB    | 640 GB  | **10 G**  | 10000GB / 月 | $249.99 / 月      | [购买](https://on.affpass.com/go/bwg/92) |
| CN2 GIA | 12 核 | 64 GB    | 1280 GB | **10 G**  | 12000GB / 月 | $479.99 / 月      | [购买](https://on.affpass.com/go/bwg/93) |
| -       | -     | -        | -       | -         | -            | -                 | -                                        |
| CN2 GIA | 1 核  | 512 MB   | 10 GB   | 1 G       | 300GB / 月   | **$39.99 / 年**   | [购买](https://on.affpass.com/go/bwg/71) |
| CN2 GIA | 1 核  | 512 MB   | 10 GB   | 1 G       | 500GB / 月   | **$49.99 / 年**   | [购买](https://on.affpass.com/go/bwg/94) |
| CN2 GIA | 2 核  | 1024 MB  | 20 GB   | 1 G       | 1000GB / 月  | **$25.99 / 季**   | [购买](https://on.affpass.com/go/bwg/72) |
| CN2 GIA | 3 核  | 2048 MB  | 40 GB   | 1 G       | 2000GB / 月  | $51.99 / 季       | [购买](https://on.affpass.com/go/bwg/73) |
| CN2 GIA | 4 核  | 4096 MB  | 80 GB   | 1 G       | 3000GB / 月  | $32.99 / 月       | [购买](https://on.affpass.com/go/bwg/74) |
| CN2 GIA | 6 核  | 8GB      | 160 GB  | 1 G       | 5000GB / 月  | $62.99 / 月       | [购买](https://on.affpass.com/go/bwg/75) |
| CN2 GIA | 8 核  | 16GB     | 320 GB  | 1 G       | 8000GB / 月  | $119.99 / 月      | [购买](https://on.affpass.com/go/bwg/76) |
| -       | -     | -        | -       | -         | -            | -                 | -                                        |
| CN2     | 1 核  | 1024 MB  | 20 GB   | 1 G       | 1000GB / 月  | **$49.99 / 年**   | [购买](https://on.affpass.com/go/bwg/57) |
| CN2     | 1 核  | 2048 MB  | 40 GB   | 1 G       | 2000GB / 月  | $52.99 / 半年     | [购买](https://on.affpass.com/go/bwg/58) |
| CN2     | 2 核  | 4096 MB  | 80 GB   | 1 G       | 3000GB / 月  | $59.99 / 季       | [购买](https://on.affpass.com/go/bwg/59) |
| CN2     | 2 核  | 8 GB     | 160 GB  | 1 G       | 5000GB / 月  | $39.99 / 月       | [购买](https://on.affpass.com/go/bwg/67) |
| CN2     | 3 核  | 16 GB    | 320 GB  | 1 G       | 8000GB / 月  | $79.99 / 月       | [购买](https://on.affpass.com/go/bwg/68) |
| -       | -     | -        | -       | -         | -            | -                 | -                                        |
| 普通    | 2 核  | 1024 MB  | 20 GB   | 1 G       | 1 TB / 月    | **$49.99 / 年**   | [购买](https://on.affpass.com/go/bwg/44) |
| 普通    | 3 核  | 2 GB     | 40 GB   | 1 G       | 2 TB / 月    | $52.99 / 半年     | [购买](https://on.affpass.com/go/bwg/45) |
| 普通    | 4 核  | 4 GB     | 80 GB   | 1 G       | 3 TB / 月    | $19.99 / 月       | [购买](https://on.affpass.com/go/bwg/46) |
| 普通    | 5 核  | 8 GB     | 160 GB  | 1 G       | 4 TB / 月    | $39.99 / 月       | [购买](https://on.affpass.com/go/bwg/47) |
| 普通    | 6 核  | 16 GB    | 320 GB  | 1 G       | 5 TB / 月    | $79.99 / 月       | [购买](https://on.affpass.com/go/bwg/48) |
| 普通    | 7 核  | 24 GB    | 480 GB  | 1 G       | 6 TB / 月    | $119.99 / 月      | [购买](https://on.affpass.com/go/bwg/49) |

选择哪个套餐？如果你不知道选择哪个套餐
下面这是最常见的购买套餐

| 线路    | CPU  | 内存    | 硬盘  | 带宽      | 流量        | 价格              | 链接                                     |
| ------- | ---- | ------- | ----- | --------- | ----------- | ----------------- | ---------------------------------------- |
| 普通    | 2 核 | 1024 MB | 20 GB | 1 G       | 1 TB / 月   | **$49.99 / 年**   | [购买](https://on.affpass.com/go/bwg/44) |
| CN2     | 1 核 | 1024 MB | 20 GB | 1 G       | 1000GB / 月 | **$49.99 / 年**   | [购买](https://on.affpass.com/go/bwg/57) |
| CN2 GIA | 1 核 | 512 MB  | 10 GB | 1 G       | 300GB / 月  | **$39.99 / 年**   | [购买](https://on.affpass.com/go/bwg/71) |
| CN2 GIA | 1 核 | 512 MB  | 10 GB | 1 G       | 500GB / 月  | **$49.99 / 年**   | [购买](https://on.affpass.com/go/bwg/94) |
| CN2 GIA | 2 核 | 1024 MB | 20 GB | 1 G       | 1000GB / 月 | **$25.99 / 季**   | [购买](https://on.affpass.com/go/bwg/72) |
| CN2 GIA | 2 核 | 1 GB    | 20 GB | **2.5 G** | 1000GB / 月 | **$65.99 / 半年** | [购买](https://on.affpass.com/go/bwg/87) |
| 香港    | 2 核 | 2048 MB | 40 GB | 1 G       | 500GB / 月  | **$89.99 / 月**   | [购买](https://on.affpass.com/go/bwg/95) |

没有找到合适的套餐？你可以前往官网详细查看：[https://bwh88.net/cart.php](https://on.affpass.com/go/bwg)

哪个套餐好？
一般来说，**推荐购买 香港线路** 或 **CN2 GIA 线路**，或者哪个便宜选择那个，说着当然如果你使用量比较多或者想要分享给同学和朋友一起用的话，选择合适的套餐即可。又或者你土豪的话，选择最贵的也行。

**VPS 速度：香港线路 > CN2 GIA 线路 > CN2 线路 > 普通线路**

**香港套餐 VPS 的速度最快。** 如果你非常在乎速度的话，建议购买香港线路的 VPS，当然，但价格贵，流量相对其他套餐来说也是比较少的……退一步的选择是 CN2 GIA 线路，这个线路的速度也比较好。

线路是比较重要的，像香港和 CN2 GIA 线路到晚上一般不会怎么炸，其他的到了晚上可能会出现很慢慢的感觉。

我本人比较推荐 CN2 GIA 线路，稳定性，速度与价格适中选择，当然啦！如果你觉得价格太贵了，推荐你查看一下[ Just My Socks ](https://justmysocks.xyz/buy-justmysocks/)，搬瓦工官方出品的代理服务，同样是 CN2 GIA 线路，**每月仅需 $2.88 起！**并且支持退款，放心无忧，再也不用自己折腾搭建了，**最最最最重要的是：被墙自动换 IP，无须担心 IP 被墙！**
Just My Socks 购买教程在这里：[ Just My Socks 详细图文购买教程](https://justmysocks.xyz/buy-justmysocks/)

毫无疑问！绝对的一分钱一分货。

>   如果出现 out of stock 这样的提示，那就是这个套餐卖完了，选择其他套餐即可。

## 添加到购物车

在上面表格中选择想要购买的套餐，然后点击 `购买` 即可。
将 VPS 添加到购物车

![Add to Cart](https://camo.githubusercontent.com/5231c8bef9232101ba25dc88f75030f3b864dc7f/68747470733a2f2f692e6c6f6c692e6e65742f323031382f31312f31382f356266313638343734323638322e706e67)

说明一下，在Billing Cycle选项那里选择：`$xxxx USD Annually`，按年付的意思

**推荐按年付，比按月付最高可省55%的钱**
Location 选择: `HK - Hong Kong xxxxx` （如果你购买的是香港线路的话）
否则选择: `US - Los Angeles xxxxx`
然后点击`Add To Cart`

## 结算

推荐使用搬瓦工 6.58% 优惠码：[BWH3HYATVBJW](https://on.affpass.com/go/bwg)

这个优惠码是搬瓦工目前最高优惠的优惠码
输入优惠码之后点击 `Validate Code >>`

![输入优惠码](https://camo.githubusercontent.com/ed446f79209aa875414ab823d7eba1c78ab42618/68747470733a2f2f692e6c6f6c692e6e65742f323031382f31312f31382f356266313638343734343233632e706e67)

然后点击 `Checkout`
如下图所示：已经使用搬瓦工优惠码

![Checkout](https://camo.githubusercontent.com/b8937e43c26d17f364b2d17ea280325dae1b6e2d/68747470733a2f2f692e6c6f6c692e6e65742f323031382f31312f31382f356266313638343730336365632e706e67)

然后会提示你注册账号 （如果你没账号或者还没登录）
请按照下面图片提示来填写~

![Checkout now](https://camo.githubusercontent.com/078e063cd7051b0eda351904a19735193593dfb7/68747470733a2f2f692e6c6f6c692e6e65742f323031382f31312f31382f356266313664613638333263362e706e67)

要注意的是，Country 选项记得选择 `China`，Payment Method 选择 `Alipay`
不要忘了勾上 I have read and agree to the Terms of Service
然后 `Complete Order`

## 付款

点击 `Pay now`
之后便会跳转到支付宝付款界面，完成付款即可

![Pay now](https://camo.githubusercontent.com/a918608ce61c5804c317efd53866fda2a14154be/68747470733a2f2f692e6c6f6c692e6e65742f323031382f31312f31382f356266313638343733323137352e706e67)

## 获取VPS信息

>   备注：按住 Ctrl + 单击， 即可在新窗口打开链接

确保你已经成功付款之后
打开：https://bwh8.net/clientarea.php?action=products
选择 `KiwiVM Control Panel`
如果出现以下界面，稍等一会，等待资源分配即可。

![Task in progress](https://camo.githubusercontent.com/11067b4314f694dfc96fae10222655b8e4ed9c11/68747470733a2f2f692e6c6f6c692e6e65742f323031372f30392f30352f353961653861386663383365322e6a7067)

等待两三分钟，刷新一下。
这是已经在运行的界面，请记下 `IP address`然后点击 `stop`

![停止VPS](https://camo.githubusercontent.com/d4ee928e535934f872362bf2ba63ebdc23f66fd2/68747470733a2f2f692e6c6f6c692e6e65742f323031382f31312f31382f356266313638343733336365632e706e67)

当出现：Great Success! Virtual server will stop in a few seconds. 相关提示
证明 VPS 已经停止了，我们需要重装一个系统。点击左边的 `Install new OS`
之后选择 `debian-9-x86_64`
再勾上：I agree that all existing data on my VPS will be lost.
然后点击 `Reload`

![Install new OS](https://camo.githubusercontent.com/3d25c0757da8b8ecaa62812053a04563310b2f47/68747470733a2f2f692e6c6f6c692e6e65742f323031382f31312f31322f356265393034633332663331622e6a7067)

当点击 `Reload` 之后，稍等片刻将会出现下图所示的界面，
请务必记下： `You will need a new root password to access your VPS：xxxx`
还有：`New SSH Port:`
一个是root密码，一个是SSH端口

![Reload](https://camo.githubusercontent.com/10063395e1bdc138ffc4923acd4c21447d323a9a/68747470733a2f2f692e6c6f6c692e6e65742f323031382f31312f31382f356266313638343733623333642e706e67)

OK，这时我们已经获取到VPS的信息了。

## 安装 Xshell

>   备注：按住 Ctrl + 单击， 即可在新窗口打开链接

Xshell 是一个易用的 SSH 客户端，要登录 VPS，当然需要 SSH 客户端

[Xshell 下载链接点我](https://fingerit-my.sharepoint.com/:u:/g/personal/ai_fingertc_com/EeP_cDRqGvpMtLoaJc1zk5AB-nDlc71rt9fQWIH4I5ShPg?e=jvAzk6)

这是一个绿色版本的 Xshell ，打开链接后，就点击 `下载`，下载好了之后，就双击打开，然后点击 `浏览...` 可以选择解压的路径，比如说 D 盘，之后再选择 `解压` 即可。

![解压 Xshell](https://camo.githubusercontent.com/33bd04fff3e18d228d241ca61ee4e3eae7a67e95/68747470733a2f2f692e6c6f6c692e6e65742f323031382f31322f32372f356332346630633939356238342e6a7067)

然后在解压的目录找到 `Xshell+Xftp 绿色版本` 文件夹，打开它，之后找到 `!安装.bat` 并且右键选择 `以管理员身份运行`，安装完成后会有一个提示窗口，关闭即可。这样来就安装好了 Xshell

![安装 Xshell](https://camo.githubusercontent.com/081b50c3fbfa3eaa1f922e8dc2fcd6d61091fdc6/68747470733a2f2f692e6c6f6c692e6e65742f323031382f31322f32372f356332346630633939393461342e6a7067)

## 登录VPS

在桌面找到 Xshell ，打开它，新建一个会话。

![新建会话](https://camo.githubusercontent.com/5dd92682b8378fda907a8b0e749464c7f195e408/68747470733a2f2f692e6c6f6c692e6e65742f323031382f31322f32372f356332346630633864373866362e6a7067)

主机写上你的 VPS IP 地址，端口写上 SSH 端口。

![new](https://camo.githubusercontent.com/84ac266197ef8856cab707c79d69276d7a18bac0/68747470733a2f2f692e6c6f6c692e6e65742f323031382f31312f31382f356266313638343733353737362e706e67)

之后点击 用户身份验证，用户名：`root`，密码：你的 root 密码。然后点击确定

![user-and-passwd](https://camo.githubusercontent.com/3314a41d15c2b9c177fcdbe7d3a2aca59875908c/68747470733a2f2f692e6c6f6c692e6e65742f323031382f31312f31382f356266313638343733376633632e706e67)

之后选择连接。

![连接](https://camo.githubusercontent.com/b77bb2449919d8ba8ba2377012692ee5764423a9/68747470733a2f2f692e6c6f6c692e6e65742f323031382f31312f31382f356266313638343733396161622e706e67)

然后会提示SSH安全警告，选择，接受并保存。

![SSH 安全警告](https://camo.githubusercontent.com/f02cefd58b2dba6607080a356d4e3c0677a4434d/68747470733a2f2f692e6c6f6c692e6e65742f323031382f31312f31382f356266313566346230346337322e706e67)

这是登录成功后的界面

![登陆成功](https://camo.githubusercontent.com/a20002103ba9858a905de077c130b23a0a28b59c/68747470733a2f2f692e6c6f6c692e6e65742f323031382f31312f31382f356266313566346230636433332e706e67)

## 安装 V2Ray

输入下面命令回车，你可以复制过去，然后在 Xshell 界面按 Shift + Insert 即可粘贴，不能按 Ctrl + V 的。。

```
bash <(curl -s -L https://git.io/v2ray.sh)
```

>   如果提示 curl: command not found ，那是因为你的 VPS 没装 Curl
>   ubuntu/debian 系统安装 Curl 方法: `apt-get update -y && apt-get install curl -y`
>   centos 系统安装 Curl 方法: `yum update -y && yum install curl -y`
>   安装好 curl 之后就能安装脚本了

然后选择安装，即是输入 1 回车
选择传输协议，如果没有特别的需求，使用默认的 TCP 传输协议即可，直接回车
选择端口，如果没有特别的需求，使用默认的端口即可，直接回车
是否屏蔽广告，除非你真的需要，一般来说，直接回车即可

![安装 V2Ray](https://camo.githubusercontent.com/734eac925355bc405fcc603dc6d44956153061b6/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30312f30352f356333303532323463666530352e6a7067)

是否配置 Shadowsocks ，如果不需要就直接回车，否则就输入 Y 回车
Shadowsocks 端口，密码，加密方式这些东西自己看情况配置即可，我个人当然是全部直接回车。。
OK，按回车继续

![配置 Shadowsocks](https://camo.githubusercontent.com/eec1b155bc310b7aaa33ae727a011a2a8625bf00/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30312f30352f356333303532323461643131632e6a7067)

安装信息，如果确保没有什么问题了，按回车继续

![安装信息](https://camo.githubusercontent.com/3b7eddf949a9d8aec9a04ae19a7bd49991817085/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30312f30352f356333303532323438636133652e6a7067)

(备注，安装信息会因你的配置而变化..不用在乎这截图)
(备注，由于我懒…脚本显示的一些信息可能会跟上面的截图有少许不同，但实际上都是很简单明了的)

## V2Ray 安装完成

OK，此时 V2Ray 已经安装完成了。

![V2Ray 安装完成](https://camo.githubusercontent.com/85637928f4e109419ff40c8c219adf6684424a4b/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30312f30352f356333303532323462626437352e6a7067)

如上图所示，V2Ray 配置信息，Shadowsocks 配置信息都有了
如果你使用过 Shadowsocks ，那么现在你可以测试一下 Shadowsocks 配置了，看看是否能正常使用。
如果你使用过 V2Ray 某些客户端，那么现在也可以测试一下配置了。
(备注，可能某些 V2Ray 客户端的选项或描述略有不同，但事实上，上面的 V2Ray 配置信息已经足够详细，由于客户端的不同，请对号入座。)

## V2Ray 客户端使用教程

暂停一下，我想，看这篇的孩子多数都是萌新，由于 V2Ray 已经安装完成了，所以此时你应该尝试使用 V2Ray 来连接上真正的互联网了。

>   Windows
>   [V2RayN使用教程](https://github.com/233boy/v2ray/wiki/V2RayN使用教程)

## V2Ray 管理面板

现在可以尝试一下输入 `v2ray` 回车，即可管理 V2Ray

![V2Ray 管理面板](https://camo.githubusercontent.com/f440719cf368dc6b6586a93afc90a4c45bede3dc/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30312f30352f356333303532323463363036652e6a7067)

## TCP 阻断

如果你觉得你的小鸡出现了这种情况，那么可以尝试使用 UDP 协议相关的 mKCP
当然，用了我的脚本那是很简单的啦，直接输入 `v2ray config` 然后选择修改 V2Ray 传输协议
之后再选择 mKCP 相关的就行咯
备注：使用 mKCP 或许还可以提高速度，但由于 UDP 的原因也许会被运营商 Qos，这是无解的。

## 快速管理 V2Ray

`v2ray info` 查看 V2Ray 配置信息
`v2ray config` 修改 V2Ray 配置
`v2ray link` 生成 V2Ray 配置文件链接
`v2ray infolink` 生成 V2Ray 配置信息链接
`v2ray qr` 生成 V2Ray 配置二维码链接
`v2ray ss` 修改 Shadowsocks 配置
`v2ray ssinfo` 查看 Shadowsocks 配置信息
`v2ray ssqr` 生成 Shadowsocks 配置二维码链接
`v2ray status` 查看 V2Ray 运行状态
`v2ray start` 启动 V2Ray
`v2ray stop` 停止 V2Ray
`v2ray restart` 重启 V2Ray
`v2ray log` 查看 V2Ray 运行日志
`v2ray update` 更新 V2Ray
`v2ray update.sh` 更新 V2Ray 管理脚本
`v2ray uninstall` 卸载 V2Ray

## 优化 V2Ray

由于本人的脚本在 Debian9 系统会自动开启 BBR 优化加速了，所以不需要再安装 BBR 优化了，
如果你还是觉得网络比较慢的话，你可以尝试使用含有 mKCP 的传输协议，这个 mKCP 的东东，简单一点说就像 Kcptun 一样加速，并且还能进行伪装 (可选)，但是由于 mKCP 是使用 UDP 协议的，也许运营商会限速得更加厉害，网络变得更加慢。但不管怎么样，你都可以随时尝试一下。
服务器输入 `v2ray config` 回车，然后选择 修改 V2Ray 传输协议，再接着选择 mKCP 相关的传输协议即可
如果你是使用其他商家的 VPS 并且是按照此教程流程来安装 V2Ray 的话，那么你可以输入 `v2ray bbr` 回车，然后选择安装 BBR 或者 锐速 来优化 V2Ray
只是还想再啰嗦一下，如果你是使用国际大厂的 VPS，并且是按照此教程流程来安装 V2Ray 的话，请自行在安全组 (防火墙) 开放端口和 UDP 协议 (如果你要使用含有 mKCP 的传输协议)

## WebSocket + TLS

实现 WebSocket + TLS 超级无敌简单，前提是要拥有一个能正常解析的域名 (并且知道怎么解析域名)
服务器输入 `v2ray config` 回车，然后选择 修改 V2Ray 传输协议，再选择 WebSocket + TLS，即是输入 4，接着输入你的域名，然后我都懒得说了，脚本都那么简单明了，我还瞎BB干嘛…
哈哈…可能有不少人在折腾 V2Ray 实现 WS + TLS 的时候真的是搞到很蛋痛咯，有些人的教程可能说得不是很清楚，或者是直接忽略小白萌新这些亲爱的用户，嗯，小白们好好加油吧，请尽量多学一些基础知识，别总是做伸手党，对于毫无交集的陌生人，人家并没有任何义务要帮你的啊
偷偷跟你说…使用 WebSocket + TLS 会有断流的问题
多说一句，不要被某些人带节奏，WS + TLS 并不是 V2Ray 的神级配置，该墙还是会墙，墙你不需要理由
备注一下啦，这里我没写怎么教你注册域名啦，怎么解析域名啦，如果你真的想要使用 WebSocket + TLS，那就 自己谷歌摸索一下，其实好简单的啦！
我本人并没有在使用 WS + TLS (WebSocket + TLS)，我用 TCP，就是用一键脚本全程回车的那种懒人

## HTTP/2

实现 HTTP/2 (h2) 也超级无敌简单，和 WebSocket + TLS 一样，也就是只要一个域名就够
服务器输入 `v2ray config` 回车，然后选择 修改 V2Ray 传输协议，再选择 HTTP/2，即是输入 16，然后………看上面的 WebSocket + TLS 的相关。
备注一下，HTTP/2 相比 WS + TLS (WebSocket + TLS) ，在浏览网页时有一些优势。速度是差不多的啦

## mKCP

mKCP 这个东东其实就是 KCP 协议，反正你知道是能提速的就行，但是不保证都能提速，还能避免 TCP 阻断，但是也可以会被运营商 Qos.
使用方法：服务器输入 `v2ray config` 回车，然后选择 修改 V2Ray 传输协议，之后再选择 mKCP 相关的就行

## 搬瓦工 VPS 速度慢

由于本教程使用了 搬瓦工 VPS 做为教程的一部分，那么相信有些新接触 VPS 的同学可能会是按照教程使用了 搬瓦工 VPS 翻墙。
如果你觉得搬瓦工 VPS 速度慢，你可以尝试修改一下端口，服务器输入 `v2ray config` ，，然后选择 修改 V2Ray 端口 即可，建议使用常见的端口，比如说 443，当然，为了更加安全隐蔽，你可以直接尝试使用 WebSocket + TLS 或者 HTTP/2 协议，但是使用这两个协议对于没有接触过 域名 的同学相对来说会是比较困难的。
搬瓦工 VPS 速度慢的一个主要原因可能会是因为端口限速，如果你已经修改端口为 443，速度还是慢的话，我建议你尝试使用 mKCP 协议。

## Telegram 专用代理

>   重要提醒：不建议使用 V2Ray 的 MTProto 代理！
>   推荐使用： https://github.com/cutelua/mtg-dist

~~如果你在使用 Telegram 的话，你可以配置一个 Telegram 的专用代理，这样来，在某些情况下你就不需要再开一个代理软件了。
输入 `v2ray tg` 即可配置 TG 专用代理
配置 Telegram MTProto~~

![配置Telegram MTProto](https://camo.githubusercontent.com/76790417fd184b9156d04f34d0020cf42e950ec9/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30312f30352f356333303532323438656137342e6a7067)

~~Telegram MTProto 配置信息~~

![Telegram MTProto 配置信息](https://camo.githubusercontent.com/f95d1c5bbe481b175defd9768972498250c7bef4/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30312f30352f356333303532323438613130662e6a7067)

## V2Ray 多用户

目前此 V2Ray 一键脚本只支持配置一个 V2Ray 账号…一个 Shadowsocks 账号
说着当然，如果你是大佬，配置 多用户 这种事，不是分分钟的事么？

## 查看配置 / 修改配置 / 端口 / 传输协议…… ？

请看上面的快速管理。。。或者直接输入 `v2ray` 回车，找到你想要执行的功能。

## 哪个传输协议好？

心中无杂念，用 TCP
ISP 常作怪，用 动态端口
小鸡速度不好，用 mKCP
处子之身，用 WS + TLS

## V2Ray 脚本说明

[V2Ray 一键安装脚本](https://github.com/233boy/v2ray/wiki/V2Ray一键安装脚本)

## 反馈问题

请先查阅：[V2Ray 一键安装脚本疑问集合](https://233v2.com/post/10/)
Telegram 群组：[ https://t.me/blog233](https://t.me/blog233)
Github 反馈：[ https://github.com/233boy/v2ray/issues](https://github.com/233boy/v2ray/issues)
任何有关于 V2Ray 的问题，请自行到 V2Ray 官方反馈。
**目前只支持配置一个 V2Ray 账号…一个 Shadowsocks 账号。。不支持 SSR。。**

## 分享

如果这篇文章对你帮助的话，记得分享给你的小伙伴们。

## 其他

请勿违反国家法律法规，否则后果自负！
低调低调低调。

## 资助 V2Ray

如果你觉得 V2Ray 很好用，能解决你的某些问题，请考虑 [资助 V2Ray 发展 ](https://www.v2ray.com/chapter_00/02_donate.html)。

## 结束

我有写少了什么吗？我这种小小白萌新看了这教程都觉得很明白了啊。
一次不会，那么就两次，还是不会，那就再来一次。可还是不会啊？大佬请收下我的膝盖。

-   **[Home](https://github.com/233boy/v2ray/wiki)**
-   **[V2RayN使用教程](https://github.com/233boy/v2ray/wiki/V2RayN使用教程)**
-   **[V2Ray一键安装脚本](https://github.com/233boy/v2ray/wiki/V2Ray一键安装脚本)**
-   **[V2Ray搭建详细图文教程](https://github.com/233boy/v2ray/wiki/V2Ray搭建详细图文教程)**
-   **[使用Cloudflare中转V2Ray流量](https://github.com/233boy/v2ray/wiki/使用Cloudflare中转V2Ray流量)**

[from 233boy 大佬](https://github.com/233boy)

**Comment by henbucuoshanghai** [comment]
等一下   请问v2ray的ubuntu怎样使用呢？

**Comment by Mm101015** [comment]
root@ser52ld7loj5nro:~# v2ray
检测到本机没安装v2ray, 正在自动安装..
Installing V2Ray v4.40.1 on x86_64
Downloading V2Ray: https://github.com/v2fly/v2ray-core/releases/download/v4.40.1/v2ray-linux-64.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   626  100   626    0     0   1682      0 --:--:-- --:--:-- --:--:--  1687
  0     0    0     0    0     0      0      0 --:--:--  0:04:38 --:--:--     0curl: (7) Failed to connect to github-releases.githubusercontent.com port 443: Connection timed out
Failed to download! Please check your network or try again.
cp: cannot create regular file '/etc/v2ray/config.json': No such file or directory
new UUID: f90b729a-fbff-11eb-9ebf-52b0a1000053
new port: 21695
sed: can't read /etc/v2ray/config.json: No such file or directory
random generate (srtp | wechat-video | utp | dtls | wireguard) fake header, new protocol: wechat 

Traceback (most recent call last):
  File "/usr/local/bin/v2ray", line 11, in <module>
    sys.exit(menu())
  File "/usr/local/lib/python3.5/dist-packages/v2ray_util/main.py", line 233, in menu
    V2ray.check()
  File "/usr/local/lib/python3.5/dist-packages/v2ray_util/util_core/v2ray.py", line 147, in check
    cls.new()
  File "/usr/local/lib/python3.5/dist-packages/v2ray_util/util_core/v2ray.py", line 171, in new
    stream.StreamModifier().random_kcp()
  File "/usr/local/lib/python3.5/dist-packages/v2ray_util/config_modify/stream.py", line 118, in random_kcp
    self.select(kcp_list[choice])
  File "/usr/local/lib/python3.5/dist-packages/v2ray_util/config_modify/stream.py", line 48, in select
    sw = StreamWriter(self.group_tag, self.group_index, sType)
  File "/usr/local/lib/python3.5/dist-packages/v2ray_util/util_core/writer.py", line 73, in __init__
    super(StreamWriter, self).__init__(group_tag, group_index)
  File "/usr/local/lib/python3.5/dist-packages/v2ray_util/util_core/writer.py", line 44, in __init__
    self.config = self.load(self.path)
  File "/usr/local/lib/python3.5/dist-packages/v2ray_util/util_core/writer.py", line 51, in load
    with open(path, 'r') as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '/etc/v2ray/config.json'

**Comment by Mm101015** [comment]
什么问题啊  老是安装不了
